##00_Pytorch_Fundamentals

In [4]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


##Introduction to tensors
## Creating tensors
##Pytorch tensors are creating using torch.tensor()



In [8]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim

0

In [10]:
#Get tensor back as python int
scalar.item()

7

In [11]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [16]:
#MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [17]:
MATRIX.ndim

2

In [18]:
MATRIX[0]

tensor([7, 8])

In [19]:
MATRIX.shape

torch.Size([2, 2])

In [20]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                         [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [21]:
TENSOR.ndim

3

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

In [23]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

## Random Tensors
why random tensors?

Random Tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

 'Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers'
