##00_Pytorch_Fundamentals

In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


##Introduction to tensors
## Creating tensors
##Pytorch tensors are creating using torch.tensor()



In [3]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Get tensor back as python int
scalar.item()

7

In [6]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                         [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

## Random Tensors
why random tensors?

Random Tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

 'Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers'


In [17]:
#Create a random tensor of size (3, 4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6863, 0.6488, 0.9108, 0.1573],
        [0.5268, 0.9878, 0.2649, 0.0920],
        [0.5800, 0.6690, 0.0919, 0.1730]])

In [18]:
random_tensor.ndim

2

In [19]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))#Height, width, color channel's
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [20]:
#Printing random tensor's
torch.rand(3, 3)

tensor([[0.9557, 0.6112, 0.7917],
        [0.5125, 0.1922, 0.1005],
        [0.8196, 0.7470, 0.8793]])

In [21]:
#Create a tensor of all zero's
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
#Create a tensors of all one's
ones = torch.ones(size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

#Creating a range of tansors and tensors-like

In [25]:
#Use torch.range()
one_to_ten = torch.arange(start = 1,end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
#Creating tensor's like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#Tensor's datatype
**Note**: Tensor datatype is one of the three big errors that you'll run into with Pytorch & Deep learning
1. Tensors not right data type
2. Tensors not right shape
3. Tensors not on the right device


In [27]:
#Float 32 tensors
float_32_tensors = torch.tensor([3.0, 6.0],
                                dtype=torch.float32,#what data type is the tensor eg float32, float16, etc
                                device = None, # device is your tensor on
                                requires_grad=False)#Track gradient's of a tensor
float_32_tensors.dtype

torch.float32

In [28]:
float_16_tensor = float_32_tensors.type(torch.float16)
float_16_tensor

tensor([3., 6.], dtype=torch.float16)

In [29]:
float_16_tensor * float_32_tensors

tensor([ 9., 36.])

In [30]:
TENSOR2 = torch.tensor([2.0, 4.0],
                      dtype = None,
                      device = None,
                      requires_grad=False)
TENSOR2

tensor([2., 4.])

In [31]:
TENSOR3 = TENSOR2.type(torch.int32)
TENSOR3

tensor([2, 4], dtype=torch.int32)

In [32]:
TENSOR4 = TENSOR3.type(torch.long)
TENSOR4

tensor([2, 4])

In [33]:
TENSOR4.dtype

torch.int64

### Gatting information from tensors

Tensors not right data type - to get datatype from a tensor, can use 'tensor.dtype'
Tensors not right shape - to get shape from a tensor, can use tensor.shape
Tensors not on the right device - to get device from a tensor can use 'tensor.device'

In [34]:
#Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8211, 0.6807, 0.4093, 0.3619],
        [0.3566, 0.1212, 0.4414, 0.9316],
        [0.6139, 0.6854, 0.4154, 0.6496]])

In [35]:
some_tensor.shape, some_tensor.size() #Same same

(torch.Size([3, 4]), torch.Size([3, 4]))

In [36]:
print(some_tensor)
print(f"Data type of tensor: {some_tensor.dtype}")
print(f"THe shape of the tensor: {some_tensor.shape}")
print(f"Device Sensor is on: {some_tensor.device}")

tensor([[0.8211, 0.6807, 0.4093, 0.3619],
        [0.3566, 0.1212, 0.4414, 0.9316],
        [0.6139, 0.6854, 0.4154, 0.6496]])
Data type of tensor: torch.float32
THe shape of the tensor: torch.Size([3, 4])
Device Sensor is on: cpu


In [37]:
random_int_tensor = torch.randint(low = 0, high = 10, size = (3, 3), dtype = torch.int64)
random_int_tensor

tensor([[3, 9, 7],
        [4, 5, 0],
        [7, 1, 6]])

 ### Manipulating Tensors (tensor's operation)

 Tensor operation include:
 * Addition
 * Subtraction
 * Multiplicatioon (ELement wise)
 * Division
 * Matrix multiplication

In [38]:
#Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [39]:
tensor * 10

tensor([10, 20, 30])

In [40]:
tensor - 10

tensor([-9, -8, -7])

In [41]:
# Try out pytorchc inbuild function
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [42]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication
Two main ways of performing matrix multiplication in neural networks are:
1. Element wise multiplication
2.Matrix multiplication

In [43]:
tensor

tensor([1, 2, 3])

In [44]:
print(tensor , "*", tensor)
print(tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
tensor([1, 4, 9])


In [45]:
## Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [46]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

CPU times: user 399 µs, sys: 815 µs, total: 1.21 ms
Wall time: 984 µs


In [47]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 152 µs, sys: 25 µs, total: 177 µs
Wall time: 154 µs


tensor(14)

### One of the most common error in deep learning is Shape Error

Shape error: torch.matmul(torch.rand(3,2), torch.rand(3,2))


torch.matmul(torch.rand(3, 2), torch.rand(2, 3)) # no error
# dimension should match
# Shape of inner dimension should match
# Resulting matrix has the shape of outer dimension

In [48]:
# Shapes for matrix multiplication

tensora = torch.tensor([[1,2],
                        [3,4],
                        [5, 6]])
tensorb = torch.tensor([[2, 3],
                        [3, 4],
                        [5,6]])
torch.matmul(tensora, tensorb)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [49]:
tensora.shape, tensorb.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

TO fix our tensor shape issues we can maipulate shape of one of our tensor using torch.transpose
Transpose switches the axes or dimensiion of a given tensor

In [50]:
tensorb, tensorb.shape

(tensor([[2, 3],
         [3, 4],
         [5, 6]]),
 torch.Size([3, 2]))

In [51]:
tensorb.T, tensorb.T.shape

(tensor([[2, 3, 5],
         [3, 4, 6]]),
 torch.Size([2, 3]))

In [52]:
torch.matmul(tensorb, tensorb.T)

tensor([[13, 18, 28],
        [18, 25, 39],
        [28, 39, 61]])

#Finding min, max, mean, sum, etc(tensor aggregation)

In [53]:
x = torch.arange(0, 100, 10)
x,  x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [54]:
torch.min(x), x.max()

(tensor(0), tensor(90))

In [55]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [56]:
x.min()

tensor(0)

In [57]:
# Find sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [66]:
#Find position of min and max on the tensor
print(torch.argmax(x))
print(torch.argmin(x))
#Also
print(x.argmin())
print(x.argmax())

tensor(9)
tensor(0)
tensor(0)
tensor(9)


#Reshaping, stacking, squeezing, and unsqueezing tensors

*Reshaping - reshapes an input tensor to a defined shape

*View - Return view of an input tensor of certain shape but keep the same memory as the original tensor

*Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)

*Squeeze - removes all `1` dimensions from a tensor

*Unsqueeze - adds a `1` dimension to a target tensor

*Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [2]:
#Creating a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [3]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [4]:
  #Change the view
  z = x.view(1, 9)
  z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [5]:
#Changing z changes x bcz view of the tensor shares the same memory as the original tensor
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [6]:
# Stack tensor on top of each other
x_stacked = torch.stack([x, x, x ,x], dim = -2)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [7]:
#Torch Unsqueeze - Adding a dimension to the tensor
x1 = torch.rand(3, 4)
x1, x1.shape

(tensor([[0.7628, 0.8924, 0.3048, 0.0590],
         [0.4181, 0.5737, 0.3480, 0.8723],
         [0.7192, 0.5020, 0.5384, 0.8018]]),
 torch.Size([3, 4]))

In [8]:
x2 = x1.unsqueeze(1)
x2, x2.shape

(tensor([[[0.7628, 0.8924, 0.3048, 0.0590]],
 
         [[0.4181, 0.5737, 0.3480, 0.8723]],
 
         [[0.7192, 0.5020, 0.5384, 0.8018]]]),
 torch.Size([3, 1, 4]))

In [9]:
#Torch Squeeze - Removes all single dimension from a tensor
x3 = x2.squeeze()
x3, x3.shape

(tensor([[0.7628, 0.8924, 0.3048, 0.0590],
         [0.4181, 0.5737, 0.3480, 0.8723],
         [0.7192, 0.5020, 0.5384, 0.8018]]),
 torch.Size([3, 4]))

In [12]:
y_original = torch.rand(size = (224, 224, 3))

#Permute the original tensor to rearrange the axis (or dim) order

y_permutted = y_original.permute(2, 0, 1)

y_original.shape, y_permutted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [15]:
x_original = torch.rand(size = (3, 2, 4))

x_original[0, 0, 0] = 7

print(f"Original: {x_original}")

x_permutted = x_original.permute(2, 0, 1)

print(f"Permutted: {x_permutted}")

x_original.shape, x_permutted.shape

Original: tensor([[[7.0000, 0.2906, 0.7088, 0.2056],
         [0.4952, 0.2018, 0.1448, 0.2825]],

        [[0.0276, 0.1149, 0.0839, 0.3663],
         [0.4959, 0.3559, 0.7288, 0.9066]],

        [[0.1374, 0.9018, 0.4175, 0.0311],
         [0.0453, 0.9024, 0.8961, 0.8975]]])
Permutted: tensor([[[7.0000, 0.4952],
         [0.0276, 0.4959],
         [0.1374, 0.0453]],

        [[0.2906, 0.2018],
         [0.1149, 0.3559],
         [0.9018, 0.9024]],

        [[0.7088, 0.1448],
         [0.0839, 0.7288],
         [0.4175, 0.8961]],

        [[0.2056, 0.2825],
         [0.3663, 0.9066],
         [0.0311, 0.8975]]])


(torch.Size([3, 2, 4]), torch.Size([4, 3, 2]))

### Indexing (Selecting data from tensors)
indexing with PyTorch is similar to indexing with NumPy

In [16]:
#Create a tensor's
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [17]:
#Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [21]:
#Let's index on the middle bracket(dim=1)
x[0][2]

tensor([7, 8, 9])

In [19]:
#Let's index on the most inner bracker(inner dimension)
x[0][0][0]

tensor(1)

In [22]:
# You can also use : to select all of target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [23]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [24]:
#Get all value of 0 dimension but only 1 index value of 1st and second dimension
x[:, 1, 1]

tensor([5])

In [25]:
#Get the index of 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [29]:
#Index on x to return 9
x[0, 2, 2]

#Index on x to return 3, 6, 9
x[0, :, 2]

tensor([3, 6, 9])

## PyTorch tensors & Numpy
NumPy is a popular scientific Python numerical computing library

And beacause of this, PyTorch has functionality to interact with it

*Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
*PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [38]:
# NumPy array to tensor

import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
tensor_float32 = tensor.type(torch.float32)
print(tensor_float32.dtype)
array, tensor

torch.float32


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [39]:
array.dtype

dtype('float64')

In [40]:
tensor.dtype
torch.arange(1.0, 8.0).dtype

torch.float32

In [41]:
#Change the vvalue of array, what will happen to tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [42]:
#Tensor to Numpy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [43]:
numpy_tensor.dtype

dtype('float32')

In [44]:
#Change the tensor, what will happen to numpy
tensor = tensor+1
numpy_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

## Reproducbility (Trying to take random out of random)
In short how a neural network learns

`start with randomm numers -> tensor operation -> update random numbers of data -> again -> again -> again`

To reduce the randomness in nn and Pytorch comes the concept of **random seed**

In [48]:
import torch

#create two random tensors

random_tensor_a = torch.rand(3, 4)
random_tensor_b = torch.rand(3, 4)
print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_b == random_tensor_a)

tensor([[0.6152, 0.3500, 0.4092, 0.0081],
        [0.7364, 0.8824, 0.0073, 0.6540],
        [0.8367, 0.9677, 0.4015, 0.9884]])
tensor([[0.7951, 0.0479, 0.4081, 0.8002],
        [0.8195, 0.8284, 0.0119, 0.4399],
        [0.9235, 0.9781, 0.2910, 0.0635]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [51]:
# Let's make some random but reproducible randoms's

import torch
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3, 4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_d == random_tensor_c)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs and making faster computation

Gpu = faster computation on numbers thanks to cuda, nvidiahardware + pytorch

### 1. Getting GPUs

Google colab
Use you own GPU - takes a little bit of setup
using cloud computing